# Generated by Django 5.1.7 on 2025-11-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birukbilugtracker',
            name='provisional',
            field=models.BooleanField(default=False, help_text='Indicates tracker with incomplete provisioning'),
        ),
    ]
