# Generated by Django 5.1.7 on 2025-11-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(db_index=True, help_text='BirukBilug tracker ID', max_length=50)),
                ('mfbr_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('boat_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('reconnecting', 'Reconnecting'), ('reconnected', 'Reconnected')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('session_start', models.DateTimeField(blank=True, help_text='Initial online timestamp for this session', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tracker Status Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tracker_id', '-timestamp'], name='api_tracker_tracker_cb6a04_idx'), models.Index(fields=['mfbr_number', '-timestamp'], name='api_tracker_mfbr_nu_305ad6_idx')],
            },
        ),
    ]
