# Generated by Django 5.2.5 on 2025-11-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_birukbilugtracker_provisional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangayverifier',
            unique_together=set(),
        ),
    ]
