# Generated by Django 5.2.5 on 2025-11-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trackerstatusevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barangayverifier',
            unique_together=set(),
        ),
    ]
