"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_pw1o3s#v1$x)ob^f#fw-2-yg!19wou6v*0m5-cg%54p48c#ls'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.100.118', '10.209.74.216', '192.168.68.83', '0.0.0.0', '*']


# Application definition

INSTALLED_APPS = [
    'corsheaders', #added
    'api.apps.ApiConfig', #added
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # WebSocket support for real-time tracking
    'rest_framework', #added
    'rest_framework_simplejwt', #added
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #added
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'api.middleware.DisableCSRFForAPIMiddleware',  # Disable CSRF for API
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Temporarily disabled for debugging
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

CORS_ALLOW_CREDENTIALS = True

# For development - allow specific origins with credentials
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://localhost:3000',
        'http://127.0.0.1:8000',
        'http://192.168.100.118:5173',
        'http://10.209.74.216:5173',
        'http://192.168.68.83:5173',
    ]

# Allow cookies to be included
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = ['Set-Cookie']


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
)

AUTH_USER_MODEL = 'api.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    "AUTH_COOKIE": "access_token",  # name of cookie
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SECURE": False,  # True in production with HTTPS
    "AUTH_COOKIE_SAMESITE": "Lax",
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_DOMAIN": None,  # Allow cookie to work on localhost
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),  # Changed to 24 hours
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # Changed to 30 days
    "ROTATE_REFRESH_TOKENS": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Channels configuration for WebSocket support
# Lazy, environment-driven configuration without connecting at import time
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],  # e.g. redis://127.0.0.1:6379/0
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_banka',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600

# Email Configuration
# For development, you can use console backend to see emails in terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production SMTP Configuration (uncomment and configure for real email sending)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change this to your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bangka.elyu@gmail.com'  # Your email address (e.g., 'your-email@gmail.com')
EMAIL_HOST_PASSWORD = 'eplo camw dkpt lrau'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'bangka.elyu@gmail.com'  # Default sender email - must match EMAIL_HOST_USER for Gmail
EMAIL_SUBJECT_PREFIX = '[Bangka] '

# Optional: Additional email settings
EMAIL_USE_SSL = False  # Don't use SSL when using TLS on port 587
EMAIL_TIMEOUT = 10  # Timeout in seconds

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =============================================================================
# SMS CONFIGURATION
# =============================================================================
# Do NOT hardcode secrets in source; set via environment variables.

# Semaphore (legacy) - keep for backward compatibility
SEMAPHORE_API_KEY = os.getenv('SEMAPHORE_API_KEY', '')
SEMAPHORE_SENDER_NAME = os.getenv('SEMAPHORE_SENDER_NAME', 'SEMAPHORE')  # up to 11 chars

# Vonage (Nexmo) SMS - HARDCODED FOR DEV ONLY
VONAGE_API_KEY = '783f5d2d'
VONAGE_API_SECRET = 'ik(ekY^ZCD41nGaHA(QwB8%EH'
VONAGE_SENDER_NAME = 'BANGKA'  # up to 11 chars

# Provider selector (hardcoded)
SMS_PROVIDER = 'vonage'  # Options: 'vonage', 'semaphore', 'itexmo'

# Generic SMS settings used by code
# Note: SMS_API_KEY is used by legacy providers (semaphore/itexmo); Vonage uses VONAGE_API_KEY/SECRET
SMS_API_KEY = SEMAPHORE_API_KEY
SMS_SENDER_NAME = VONAGE_SENDER_NAME if SMS_PROVIDER == 'vonage' else SEMAPHORE_SENDER_NAME

# Boundary alert policy: boat must stay in new municipality for this many minutes before alert
BOUNDARY_DWELL_MINUTES = 15  # Standard dwell time before violation alert

# Idle detection: boat considered idle if it hasn't moved this many meters in dwell period
IDLE_DETECTION_METERS = 50  # If boat moves less than 50m, it's considered idle/stationary

# Temporary: include points very near the border as inside (degrees; ~111,320m per degree)
# 0.00030 ≈ 33 meters. Reduce back to 0.00020 (~22m) or 0 in production if not desired.
BOUNDARY_EDGE_TOLERANCE_DEG = 0.00020

