// src/constants/fisherfolkOptions.js

export const municipalityPrefixes = {
  Agoo: "AGO",
  Aringay: "ARI",
  Bacnotan: "BAC",
  Bagulin: "BAG",
  Balaoan: "BAL",
  Bangar: "BNG",
  Bauang: "BAU",
  Burgos: "BRG",
  Caba: "CAB",
  "San Fernando": "SFN",
  "City of San Fernando": "CSF",
  Luna: "LUN",
  Naguilian: "NAG",
  Pugo: "PUG",
  Rosario: "ROS",
  "San Gabriel": "SGB",
  "San Juan": "SJN",
  "Santo Tomas": "STO",
  Santol: "SNL",
  Sudipen: "SUD",
  Tubao: "TUB",
};


export const barangayOptions = {
  Agoo: [
    "Ambitacay",
    "Balawarte",
    "Capas",
    "Consolacion",
    "Macalva Central",
    "Macalva Norte",
    "Macalva Sur",
    "Nazareno",
    "Purok",
    "San Agustin East",
    "San Agustin Norte",
    "San Agustin Sur",
    "San Antonino",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Joaquin Norte",
    "San Joaquin Sur",
    "San Jose Norte",
    "San Jose Sur",
    "San Juan",
    "San Julian Central",
    "San Julian East",
    "San Julian Norte",
    "San Julian West",
    "San Manuel Norte",
    "San Manuel Sur",
    "San Marcos",
    "San Miguel",
    "San Nicolas Central",
    "San Nicolas East",
    "San Nicolas Norte",
    "San Nicolas Sur",
    "San Nicolas West",
    "San Pedro",
    "San Roque West",
    "San Roque East",
    "San Vicente Norte",
    "San Vicente Sur",
    "Santa Ana",
    "Santa Barbara",
    "Santa Fe",
    "Santa Maria",
    "Santa Monica",
    "Santa Rita (Nalinac)",
    "Santa Rita East",
    "Santa Rita Norte",
    "Santa Rita Sur",
    "Santa Rita West",
  ],
  Aringay: [
    "Alaska",
    "Basca",
    "Dulao",
    "Gallano",
    "Macabato",
    "Manga",
    "Pangao-aoan East",
    "Pangao-aoan West",
    "Poblacion",
    "Samara",
    "San Antonio",
    "San Benito Norte",
    "San Benito Sur",
    "San Eugenio",
    "San Juan East",
    "San Juan West",
    "San Simon East",
    "San Simon West",
    "Santa Cecilia",
    "Santa Lucia",
    "Santa Rita East",
    "Santa Rita West",
    "Santo Rosario East",
    "Santo Rosario West",
  ],
  Bacnotan: [
    "Agtipal",
    "Arosip",
    "Bacqui",
    "Bacsil",
    "Bagutot",
    "Ballogo",
    "Baroro",
    "Bitalag",
    "Bulala",
    "Burayoc",
    "Bussaoit",
    "Cabaroan",
    "Cabarsican",
    "Cabugao",
    "Calautit",
    "Carcarmay",
    "Casiaman",
    "Galongen",
    "Guinabang",
    "Legleg",
    "Lisqueb",
    "Mabanengbeng 1st",
    "Mabanengbeng 2nd",
    "Maragayap",
    "Nangalisan",
    "Nagatiran",
    "Nagsaraboan",
    "Nagsimbaanan",
    "Narra",
    "Ortega",
    "Paagan",
    "Pandan",
    "Pang-pang",
    "Poblacion",
    "Quirino",
    "Raois",
    "Salincob",
    "San Martin",
    "Santa Cruz",
    "Santa Rita",
    "Sapilang",
    "Sayoan",
    "Sipulo",
    "Tammocalao",
    "Ubbog",
    "Oya-oy",
    "Zaragosa",
  ],
  Bagulin: [
    "Alibangsay",
    "Baay",
    "Cambaly",
    "Cardiz",
    "Dagup",
    "Libbo",
    "Suyo",
    "Tagudtud",
    "Tio-angan",
    "Wallayan",
  ],
  Balaoan: [
    "Almieda",
    "Antonino",
    "Apatut",
    "Ar-arampang",
    "Baracbac Este",
    "Baracbac Oeste",
    "Bet-ang",
    "Bulbulala",
    "Bungol",
    "Butubut Este",
    "Butubut Norte",
    "Butubut Oeste",
    "Butubut Sur",
    "Cabuaan Oeste",
    "Calliat",
    "Calungbuyan",
    "Camiling",
    "Dr. Camilo Osias",
    "Guinaburan",
    "Masupe",
    "Nagsabaran Norte",
    "Nagsabaran Sur",
    "Nalasin",
    "Napaset",
    "Pagbennecan",
    "Pagleddegan",
    "Pantar Norte",
    "Pantar Sur",
    "Pa-o",
    "Paraoir",
    "Patpata",
    "Sablut",
    "San Pablo",
    "Sinapangan Norte",
    "Sinapangan Sur",
    "Tallipugo",
  ],
  Bangar: [
    "Agdeppa",
    "Alzate",
    "Bangaoilan East",
    "Bangaoilan West",
    "Barraca",
    "Cadapli",
    "Caggao",
    "Consuegra",
    "General Prim East",
    "General Prim West",
    "General Terrero",
    "Luzong Norte",
    "Luzong Sur",
    "Maria Cristina East",
    "Maria Cristina West",
    "Mindoro",
    "Nagsabaran",
    "Paratong Norte",
    "Paratong No. 3",
    "Paratong No. 4",
    "Central East No. 1",
    "Central East No. 2",
    "Central West No. 1",
    "Central West No. 2",
    "Central West No. 3",
    "Quintarong",
    "Reyna Regente",
    "Rissing",
    "San Blas",
    "San Cristobal",
    "Sinapangan Norte",
    "Sinapangan Sur",
    "Ubbog",
  ],
  Bauang: [
    "Acao",
    "Baccuit Norte",
    "Baccuit Sur",
    "Bagbag",
    "Ballay",
    "Bawanta",
    "Boy-utan",
    "Bucayab",
    "Cabalayangan",
    "Cabisilan",
    "Calumbaya",
    "Carmay",
    "Casilagan",
    "Central East",
    "Central West",
    "Dili",
    "Disso-or",
    "Guerrero",
    "Nagrebcan",
    "Pagdalagan Sur",
    "Palintucang",
    "Palugsi-Limmansangan",
    "Parian Oeste",
    "Parian Este",
    "Paringao",
    "Payocpoc Norte Este",
    "Payocpoc Norte Oeste",
    "Payocpoc Sur",
    "Pilar",
    "Pudoc",
    "Pottot",
    "Pugo",
    "Quinavite",
    "Lower San Agustin",
    "Santa Monica",
    "Santiago",
    "Taberna",
    "Upper San Agustin",
    "Urayong",
  ],
  Burgos: [
    "Agpay",
    "Bilis",
    "Caoayan",
    "Dalacdac",
    "Delles",
    "Imelda",
    "Libtong",
    "Linuan",
    "New Poblacion",
    "Old Poblacion",
    "Lower Tumapoc",
    "Upper Tumapoc",
  ],
  Caba: [
    "Bautista",
    "Gana",
    "Juan Cartas",
    "Las-ud",
    "Liquicia",
    "Poblacion Norte",
    "Poblacion Sur",
    "San Carlos",
    "San Cornelio",
    "San Fermin",
    "San Gregorio",
    "San Jose",
    "Santiago Norte",
    "Santiago Sur",
    "Sobredillo",
    "Urayong",
    "Wenceslao",
  ],
  "San Fernando": [
    "Abut",
    "Apaleng",
    "Bacsil",
    "Bangbangolan",
    "Bangcusay",
    "Barangay I",
    "Barangay II",
    "Barangay III",
    "Barangay IV",
    "Baraoas",
    "Bato",
    "Biday",
    "Birunget",
    "Bungro",
    "Cabaroan",
    "Cabarsican",
    "Cadaclan",
    "Calabugao",
    "Camansi",
    "Canaoay",
    "Carlatan",
    "Catbangen",
    "Dallangayan Este",
    "Dallangayan Oeste",
    "Dalumpinas Este",
    "Dalumpinas Oeste",
    "Ilocanos Norte",
    "Ilocanos Sur",
    "Langcuas",
    "Lingsat",
    "Madayegdeg",
    "Mameltac",
    "Masicong",
    "Nagyubuyuban",
    "Namtutan",
    "Narra Este",
    "Narra Oeste",
    "Pacpaco",
    "Pagdalagan",
    "Pagdaraoan",
    "Pagudpud",
    "Pao Norte",
    "Pao Sur",
    "Parian",
    "Pias",
    "Poro",
    "Puspus",
    "Sacyud",
    "Sagayad",
    "San Agustin",
    "San Francisco",
    "San Vicente",
    "Santiago Norte",
    "Santiago Sur",
    "Saoay",
    "Sevilla",
    "Siboan-Otong",
    "Tanqui",
    "Tanquigan",
  ],
  Luna: [
    "Alcala",
    "Ayaoan",
    "Barangobong",
    "Barrientos",
    "Bungro",
    "Buselbusel",
    "Cabalitocan",
    "Cantoria No. 1",
    "Cantoria No. 2",
    "Cantoria No. 3",
    "Cantoria No. 4",
    "Carisquis",
    "Darigayos",
    "Magallanes",
    "Magsiping",
    "Mamay",
    "Nagrebcan",
    "Nalvo Norte",
    "Nalvo Sur",
    "Napaset",
    "Oaqui No. 1",
    "Oaqui No. 2",
    "Oaqui No. 3",
    "Oaqui No. 4",
    "Pila",
    "Pitpitac",
    "Rimos No. 1",
    "Rimos No. 2",
    "Rimos No. 3",
    "Rimos No. 4",
    "Rimos No. 5",
    "Rissing",
    "Salcedo",
    "Santo Domingo Norte",
    "Santo Domingo Sur",
    "Sucoc Norte",
    "Sucoc Sur",
    "Suyo",
    "Tallaoen",
    "Victoria",
  ],
  Naguilian: [
    "Aguioas",
    "Al-alinao Norte",
    "Al-alinao Sur",
    "Ambaracao Norte",
    "Ambaracao Sur",
    "Angin",
    "Balecbec",
    "Bancagan",
    "Baraoas Norte",
    "Baraoas Sur",
    "Bariquir",
    "Bato",
    "Bimmotobot",
    "Cabaritan Norte",
    "Cabaritan Sur",
    "Casilagan",
    "Dal-lipaoen",
    "Daramuangan",
    "Guesset",
    "Gusing Norte",
    "Gusing Sur",
    "Imelda",
    "Lioac Norte",
    "Lioac Sur",
    "Mangungunay",
    "Mamat-ing Norte",
    "Mamat-ing Sur",
    "Nagsidorisan",
    "Natividad",
    "Ortiz",
    "Ribsuan",
    "San Antonio",
    "San Isidro",
    "Sili",
    "Saguidan Norte",
    "Saguidan Sur",
    "Tuddingan",
  ],
  Pugo: [
    "Ambalite",
    "Ambangonan",
    "Cares",
    "Cuenca",
    "Duplas",
    "Maoasoas Norte",
    "Maoasoas Sur",
    "Palina",
    "Poblacion East",
    "Poblacion West",
    "San Luis",
    "Saytan",
    "Tavora East",
    "Tavora Proper",
  ],
  Rosario: [
    "Alipang",
    "Ambangonan",
    "Amlang",
    "Bacani",
    "Bangar",
    "Bani",
    "Benteng-Sapilang",
    "Cadumanian",
    "Camp One",
    "Carunuan East",
    "Carunuan West",
    "Casilagan",
    "Cataguingtingan",
    "Concepcion",
    "Damortis",
    "Gumot-Nagcolaran",
    "Inabaan Norte",
    "Inabaan Sur",
    "Nagtagaan",
    "Nangcamotian",
    "Parasapas",
    "Poblacion East",
    "Poblacion West",
    "Puzon",
    "Rabon",
    "San Jose",
    "Marcos",
    "Subusub",
    "Tabtabungao",
    "Tanglag",
    "Tay-ac",
    "Udiao",
    "Vila",
  ],
  "San Gabriel": [
    "Amontoc",
    "Apayao",
    "Balbalayang",
    "Bayabas",
    "Bucao",
    "Bumbuneg",
    "Lacong",
    "Lipay Este",
    "Lipay Norte",
    "Lipay Proper",
    "Lipay Sur",
    "Lon-oy",
    "Poblacion",
    "Polipol",
    "Daking",
  ],
  "San Juan": [
    "Allangigan",
    "Aludaid",
    "Bacsayan",
    "Balballosa",
    "Bambanay",
    "Bugbugcao",
    "Caarusipan",
    "Cabaroan",
    "Cabugnayan",
    "Cacapian",
    "Caculangan",
    "Calincamasan",
    "Casilagan",
    "Catdongan",
    "Dangdangla",
    "Dasay",
    "Dinanum",
    "Duplas",
    "Guinguinabang",
    "Ili Norte",
    "Ili Sur",
    "Legleg",
    "Lubing",
    "Nadsaag",
    "Nagsabaran",
    "Naguirangan",
    "Naguituban",
    "Nagyubuyuban",
    "Oaquing",
    "Pacpacac",
    "Pagdildilan",
    "Panicsican",
    "Quidem",
    "San Felipe",
    "Santa Rosa",
    "Santo Rosario",
    "Saracat",
    "Sinapangan",
    "Taboc",
    "Talogtog",
    "Urbiztondo",
  ],
  "Santo Tomas": [
    "Ambitacay",
    "Bail",
    "Balaoc",
    "Balsaan",
    "Baybay",
    "Cabaruan",
    "Casantaan",
    "Casilagan",
    "Cupang",
    "Damortis",
    "Fernando",
    "Linong",
    "Lomboy",
    "Malabago",
    "Namboongan",
    "Namonitan",
    "Narvacan",
    "Patac",
    "Poblacion",
    "Pongpong",
    "Raois",
    "Tubod",
    "Tococ",
    "Ubagan",
  ],
  Santol: [
    "Corrooy",
    "Lettac Norte",
    "Lettac Sur",
    "Mangaan",
    "Paagan",
    "Poblacion",
    "Puguil",
    "Ramot",
    "Sapdaan",
    "Sasaba",
    "Tubaday",
  ],
  Sudipen: [
    "Bigbiga",
    "Bulalaan",
    "Castro",
    "Duplas",
    "Ilocano",
    "Ipet",
    "Maliclico",
    "Namaltugan",
    "Old Central",
    "Poblacion",
    "Porporiket",
    "San Francisco Norte",
    "San Francisco Sur",
    "San Jose",
    "Sengngat",
    "Turod",
    "Up-uplas",
  ],
  Tubao: [
    "Amallapay",
    "Anduyan",
    "Caoigue",
    "Francia Sur",
    "Francia West",
    "Garcia",
    "Gonzales",
    "Halog East",
    "Halog West",
    "Leones East",
    "Leones West",
    "Linapew",
    "Magsaysay",
    "Pideg",
    "Poblacion",
    "Rizal",
    "Santa Teresa",
    "Lloren",
  ],
};

export const organizationOptions = {
  Bangar: {
    Mindoro : ['Mindoro Fisherfolk Association', 'Mindoro Daya Fisherfolk Association', 'Northern Mindoro Fisherfolk Association', 'Puso ng Kababaihan Fisherfolk Association', 'Others'],
    'Paratong Norte': ['Paratong Norte Fisherfolk Association', 'Busilac Bangus & Tilapia Fishcages Growers Association', 'Bangar Solar Sea Salt Fisherfolk Association', 'Others'],
    'Paratong No. 3': ['Paratong 3 Fisherfolk Association', 'Bangus Smoked & Marinated Fisherfolk Association', 'Others'],
    'Paratong No. 4': ['Paratong 4 Fisherfolk Association', 'Others'],
  },
  Balaoan: {
    Paraoir:['Women Aquatic Processing Association', 'Aksyon Paraoir Livelihood Association', 'Others'],
    Almeida: ['Almeida Fisherfolk Association', 'Others'],
  },
  Luna :{
    Darigayos: ['Amianan Fishermen Progress', 'Spencer Fishermen Association', 'Lakon Association', 'Bannuar Fisherfolks Association', 'Mekus Mekus Fishermen Association', 'Others'],
    Carisquis: ['Brgy. Carisquis Farmers and Fisherfolks Association Inc', 'Others'],
    'Nalvo Sur': ['Gaget Nalvo Sur Farmers Association Inc', 'Others'],
    'Nalvo Norte' :['Panagkakadwa Dagiti Mangngalap Iti Nalvo Norte', 'Others'],
    Barrientos: ['Brgy. Barrientos Farmers Raisers Association Inc', 'Others'],
    Magallanes: ['Association Of Farmers and Fisherfolks In Magallanes Luna La Union Inc', 'Others'],
    Victoria: ['Assosasyon Ti Mannalon Ken Mangngalap Iti Barangay Victoria, Luna Inc.', 'Others'],
    'Sto. Domingo Sur': ['Sto Domingo Sur Fisher Folks Inc', 'Others'],
    'Sto. Domingo Norte':['Sto Domingo Norte Fishing Organization Inc', 'Others'],
    'Rimos No. 1': ['Rimos #1 Farmers And Fisherfolks Association Inc', 'Others'],
    'Rimos No. 2': ['United R-2 And R-3 Farmers Fishers Associton Inc', 'Others'],
    'Rimos No. 3': ['United R-2 And R-3 Farmers Fishers Associton Inc', 'Others'],
    'Rimos No. 4': ['Rimos 4 Assosasyon Ti Mangngalap', 'Others'],
    'Rimos No. 5': ['Rimos 5 Fishermen Association', 'Others'],
  },
  Bacnotan: {
    Quirino: ['Quirino Fishermen Cooperative', 'Others'],
    Baroro: ['Asosasyon iti Mangalap ken Mannalao iti Baroro, Bacnotan, Inc.', 'Others'],
    Tammocalao: ['Tammocalao Fisherfolk Association', 'Others']
  },
  'San Juan': {
    Taboc: ['Taboc Fishermen Association', 'Others'],
    Panicsican: ['Panicsican Farmers and Fisherfolk Association Inc.', 'Others']
  },
  Bauang: {
    'Pagdalagan Sur': ['Pagdalagan Sur Fisherfolks Navigator Association', 'Others'],
    Paringao: ['Paringao Fisherfolks Association', 'Others'],
    'Baccuit Norte': ['Fisherfolks Association of Baccuit norte', 'Others'],
    'Baccuit Sur': ['United Fisherfolks Association of Baccuit Sur', 'Others'],
    Taberna: ['Fishermen Association of Taberna', 'Others'],
    Pugo: ['Brgy. Pugo Fisherfolks Association', 'Others'],
    'Parian Oeste': ['Bauang Fishing Group Consumer Cooperative', 'Others'],
    Pudoc: ['Pudoc Fisherfolks Association', 'Others'],
    'Payocpoc Norte Oeste': ['Sea Fighters Fisherfolks Association', 'Others'],
    Santiago: ['Santiago&#39; s Best Fisherfolks Association', 'Others'],
    Pilar: ['Pilar&#39;s Best Fisherfolks Association', 'Others'],
    Bagbag: ['Asosasyon Ti mangngalap ti Laud', 'Others'],
  },
  Caba: {
    'Santiago Sur': ['Fishermen and Farmer&#39;s Association, Inc.', 'Santiago Sur Operators and Fisherfolks Association', 'Others'],
  },
    Aringay: {
    Samara: ['United Samara Fisherfolk Association', 'D&#39; Marylanders Fisherfolk Association', 'Others'],
    'Santa Lucia': ['Gunglo ti Mangngalap ti Sta Lucia', 'Sta Lucia Fisherfolk Association', 'Others'],
    Alaska: ['Alaska Fisherfolk Association', 'Nagpanawan Kingfisher Fisherfolk Association', 'Others'],
    'Santo Rosario West': ['Sto Rosario Fisherfolk Association', 'Others'],
    'Santo Rosario East': ['Sanggir ti Mangngalap ti Sto. Rosario East', 'Others'],
    'Dulao': ['Dulao United Fisherfolk Association', 'Dulao Fishpond and Fishpen Producers Cooperative', 'Others'],
  },
  Agoo: {
    'Santa Rita': ['Sta. Rita Sur Farmers and Fisherfolks Association', 'Others'],
    'San Julian West': ['San Julian West Fisherfolk Association', 'Others'],
    'San Manuel Norte': ['San Manuel Norte Farmer. and Fisherfolk Association', 'Others'],
    Balawarte: ['Timpuyog ti Mangngalap iti Barangay Balawarte', 'Others'],
    'Santa Rita Central': ['Fishermen Association of Sta. Rita Central', 'Others'],
    'San Isidro': ['San Isidro Timpuyog Agriculture Cooperative', 'Others'],
    'San Nicolas West': ['Panagcaycaysa Iti Mangalap ti Barangay San Nicolas West', 'Others']
  },
  'Santo Tomas': {
    Ubagan: ['Ubagan Fisherfolks Association', 'Ubagan Seaside SLP Association', 'Ubagan Fish Culture SLP Association', 'Others'],
    Damortis: ['Damortis Fisherfolks Fishermen Cooperative (OFFC)', 'Others'],
    Narvacan: ['Narvacan Fishers Agriculture Cooperative', 'Others'],
    Manonitan: ['Namonitan Fisherfolks Association', 'Others'],
    Cupang: ['Cupang United Fisherfolks Association', 'Timpuyog Dagiti Taksayan Association', 'Others'],
    Tubod: ['Samahang Mandaragat ng Barangay Tubod', 'Others']
  },
  Rosario: {
    Rabon: ['Rabon Fisherfolk Association', 'Others'],
    Bani: ['Mangngalap ti Laud Bani', 'Bani Wave Breakers Association', 'Others']
  }
};